sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t jsuleto/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jsuleto/docker-react npm run test
